apiVersion: v1
kind: Service
metadata:
  name: argoos
  namespace: kube-system
  labels:
    app: argoos
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: argoos
  type: ClusterIP

# vim:ft=yaml:et:sw=2:ts=2:sts=2:
