apiVersion: v1
kind: ReplicationController
metadata:
  name: argoos
  namespace: kube-system
spec:
  replicas: 1
  selector:
    app: argoos
  tempate:
    metadata:
      labels:
        app: argoos
    spec:
      containers:
      - image: smilelab/argoos
        name: argoos
        ports:
        - containerPort: 3000
        livenessProbe:
        httpGet:
          # Path to probe; should be cheap, but representative of typical behavior
          path: /healthz
          port: 3000
        initialDelaySeconds: 30
        timeoutSeconds: 1

